# Generated by Django 6.0.5 on 2026-05-21 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('case_type', models.CharField(blank=True, choices=[('Physical', 'Physical'), ('Emotional', 'Emotional'), ('Sexual', 'Sexual'), ('Economic', 'Economic'), ('Harassment', 'Harassment')], max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('date_of_incident', models.DateField(blank=True, null=True)),
                ('time_of_incident', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Submitted', max_length=50)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
