# Generated by Django 6.0.5 on 2026-05-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='admin_response',
            field=models.TextField(blank=True),
        ),
    ]
